# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [zacks, battle]
patreon: # Replace with a single Patreon usernames mouse3687
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username stingray
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username WAPT
issuehunt: # Replace with a single IssueHunt username reeds
otechie: # Replace with a single Otechie username Smith
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://dhs.gov','https://cdc.gov', 'https://noon.com']
